#
# This file contains configuration flags to customize your site
#

# Name of your site (displayed in the header)
name: Blog

# Short bio or description (displayed in the header)
description: Jorge García Carrasco

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wCEAAkGBxASEhUQEhAVFRISEA8SFRAQDxAPEBAQFRUWFhUSFRUYHSggGBolGxUVITEhJSkrLi4uFx8zODMtNygtLisBCgoKDg0OGBAQFSsdFR0rLSsrLSsrKy0tLS0tKy0uKy0tLS0rLS03LTc3NystKy03KysrLSsrKysrKysrLSsrK//AABEIAOEA4QMBIgACEQEDEQH/xAAbAAABBQEBAAAAAAAAAAAAAAAEAAIDBQYBB//EAD4QAAEDAwIDBQUFBwIHAAAAAAEAAgMEESEFMRJBUQYTImFxMoGRkqEUFTNSsQcjQlNiwdFDciQ0VILh8PH/xAAZAQADAQEBAAAAAAAAAAAAAAAAAQIDBAX/xAAiEQEBAQEAAgIDAAMBAAAAAAAAAQIRAyESMQQTQVFhcSL/2gAMAwEAAhEDEQA/AKg6DSf9PH8jVD9x01/wI/kCuiFARlScVFZo9OD+Czb8oTIdHprZhZ8oR9XKCbLsIwg6qqnSKYbQs+UKeLRqa1+5Z8oU1X7QRUOyCVX3PT8X4LPlCfJpFMB+Az5AjGe0pJzhAVcOkU5/0WfKEPXaVA0Yhb8oVtAMKLUtreSCVdFpcJbcwsP/AGhSfdcF7dyz5QjNOBDco2Gj4g9+wb+qm1Uir+6YP5LPlChbpdOTbumfKFqKCjaXMDz7R28kRqekQxOLi4Bo88lT+zip4+s5TdnIZMNiZ68IRUPY2MHxRs+QK6pdYpo7NYMk7lHyavFckuAsNuqzvk11pPHP6yc3ZBlriFp3/hCttJ7E0/BxSxMuRsWjCKre0sYFmbhU0/aNx3dYX6pfs2fwzE+p9jqdgsyFpvseEbqmqOzbI/agbYWzwhaCbtQwx2bl1sHzRtLXMlYGy7G2b80871/U68cvuPP67S42/wCk3Iv7IUEFDER+G35Qtv2n0xrgDGL3AAAWZNI+PwuFitZvrO54Fi0+IkXjZ8oTqzT4QbCJvyhF0/thS1cVyqiOqv7vh/lN+UJzdNh/lN+UIhwthEQsTCtnoIQfwm/KFG+hi/lt+UI2tOVxjLhIAvsMX8tvwC4rDuvJcQGzthDHc+iLcMIF25VURVEkyFHQ7KvjPjcVZQ7BIwtWPEETHsh6z2giI9kBDF7SfPso4j4ipJ9kA2nCjq+SkgUVUdvIoIRSx8rb+Sv9PpW/Zzx4Bcg9NqyQGlgO226j1DUfDwNwGOyL7rHTfMh1fUsaS4bgYA5LPV1e57buJJ803VNVt4Wt9ofVU9PDNJ6dFMkn2v8A4lbNY3uoZJXPdfiPorWPQpCMpsuiSNzZPsL46Vglda/6oGVznOtf3Kwmopc4KCbSvZkjKuWJua42Ys57KxpdTcS1t8A3VTJC4m5RFAMgeaWuUR6ppR4om9UB2p00+GTlw5slpdc0ANvyCtpXB8djsVl3irOxhYYTxAgYU7zlX09K0NIAsB9VQzHK3zrrn1niuqL8WEbDsoHDxKdpVpA1jLlT0rMZUkoF11qAbwpJySRtW8YVa/c+hR734VbO7f0KulFXB7TvVWcOwVXSH2j5lHwS2Ck0dX7Snj2QlRJcqeJ+EA2H2ipJjhQRO8SfM7CA7AoqkZXIZE5jOJ4CVODG1HcxF9snAVZUZbxXycnqje0MpHDG22BkKrjJ4T5rKt8xJpVD3r/IdVq6egY0YCE7O0nC29slXYasN6dWM8iAR4TXR4yibpkiz604BNM3oENUaax3IKxsuOCuaqbmMhqGj9AqpumvbmxXoPADyRFNRMdjh3VzVY6xGFpZeFaGgrOMtF8DdCdq9K7nxjYqt0irIPC3Ku+4y/rX1dnC2w/VZqtYQ44wr2F7iM/+FW6zU2swWPVyfjqPJxTP3UrUO45UzVswJ6QXHFcumZcaSjSSC3dqLbIWStBuFYyaSAo5dOaGk+Sq0cUsMwFxdSsqQhaaPieRbmr2LSm22SCnlq8qWOsFlaO0lvRQv0xvRLoANrAnOqwRhTP09vRN+7+iOnxD39kdpLuJxfyaPqoPsKtdOg4IyerrKdX0vE9q+Y8biT7XXyUmnUJe/wAlNUR2JPP/ACr3SaXhZ6rDWnXjIyCINbYBOISkNkFNVEcllzrbol6iJQLtSt7SdHqDHJXJ9EkrhTOMFOJVCkEbSGyCCLpmpxnoRq9A2eJzXflXn2jQhs3D0J+i9IL7NPoVjNOpP+JLi244iVpz0wonWZeGzWmzrZF+SzFTVG/iH91pO08bXEOB8Q/RZx9KVpmOfd6hMovhPFUF37KuilC0QhfVhIVCIFGEvsKQD94uIn7D5pIDbFtygdVbZh9FaRtHXKD1dl2EDdPhsjpjfHfzWqj2VDp1MQcrQxx4ufiiwjXNQ8gRsM7C4M3JR1TpVhjBPVLhs86NcYxH1FK5u4UUEJLgOu6L6nRmfK8RNpnHZpRrae0Q83bo+nJLuFos0fVd1KmcWENdgZsufXk675+NczqpnpQXAcy7PuV5GMKt0dhd4nb7KyJWOq0zHHgIVz2A5I+Kne4oWSlBN7C/mnmnYDrHQnFx/dV4pm38JUOq6W8v4xj0NgpNIp38WVdKdWUFO4DKUswarFwws92jdwBptuoiteokl1ljTYo7T9cicQCcLKxU7JN3I5umNYLtK14wt6380QLOJuxGCq3R4wXPJxbmiuzUxfAWndoNkIfBDI78xx+itjpmdTdd7v8AcUJwoiUXN+aYQtpPTnqF7F1rLKcsTHhMjEguLqQdukuWXUjT/fL3YJsfJNfVnfiKppDbKFqqo7ArSVPF+6UtHEPip49V8PA4781VafUccZjO+6idCQAVc9otXmkyAy3HI3VzrepF5ADrFvMLKaRPZ49VqDBFIcOs6yYCs1It9t9x5oqgrI3OPDvwlPMFPGC2YehsqnTe7ZUeE2Ybgf2WPkvct/D63F7FJwNDjz5IuCXiFrWBG90JW0rncPDyKMhItbmvPr2/JqWJKeENbhcsphsouanXtjgxzENISEYUPK1Lh8AyR8W6IpoQ0bKOU22T5qljGgyPDQbblX7o+jpDuqftRSccLT5/BWpmYW8QNx1CmicySAt3sVWUeS+nnTqR7rcOCOmLrS6RDMGWkaSPzW2Uhog12FpdHNm8O481pdOf4pOzENmu8wVUdoZOFjWdSSbeq1tPAGAkcwVAIqaVliATsT0WmIy8vt5yZW9UNPVNBsMjqju13Zru7vieeHpdZqF5twc7breT05WjonB4woqocO6DoaoxNwLnqmS1rnHicUySCpaTa+VK3Ky0s7uIkHmtF2crGE8EhtfFykBHC7oktJ93QfzB8UkcPrzupqbjZCNF8qRzwVwjGFPTF6If3m6u9QaGj1WYgaWm98q6fUXDb9Fri/8AlFntDTSO4vCCT5BXscVQSHCN1wOihoaxjACGi61uha2DggXS6rjGa1q75iIS0tIIvcKSppnNaCNwAfer7tbShzxUMaCQMgBUFNWl4N9hySs9D5crR9n9YbK0McbSDBBNr+iuCvOaiRtwW4I5jC9A7IfvIC94ub2uVyeXx/F3+Hz/ACnKLGyjupp22UDVzuqOqGVTqCVA6DLblD1FGx5u8cQHI7Iqw6qCaUDF1chdtC6g0cBawWxy5Ku0F8sbXB7r32vyVtE8X39yO7pjxa1imjV59gqc8QyVZULrEBCil4MIulZkeqSNWfxfVdUGQFx9Fj6uubHIx8ZLQ8eJt8eqvtZkwIerLrH6xpMr3tIcAGgAe9a+LXNz/BebGf19/qx1yovHe+CFhGSBsvkVvaDT3htpSHN9VDqeh0/tNaL2XZrc+3nTOvpmJZWgY2OVT6k53DhaOn09wPiZdqF1HSZX/hss1Z/KKmKyLZORVloTeN9vMWRE/Zeo37s+qjo9IqYncXdlOaguK1n2Z3T6pIDv6j8hSW37Msfhplo0RAEHC/KMpzlYtUh3RFQcBCyFT1BuwK8fSdJIJchXunSZCzEb7FW9DVWsnnha629PUBwsRfCzer6eYiXsGCb2R1LPsbq37sSNI3wtv1yxEvKx9NSmTNl6F2dh7qn9XXWeoKXhJxzstPOeGMDyXL+TJmOr8X3Ude7OPJCOdlMmnNsrnFcXXnPTlTB6hqXcWFzjTS5OFoE6ize5+KEq6cfmI991aOcqqraSVcpy+kMdK/k7PLqiIa9zCGSAh18HkQhOFw5omR3eNs7JH8R3CrrPd61DrOAPUKekp/EDyGVW6dKOCx5K4dO1kfGTsFU4x7xWav4XulcbBrLBYmepc4k8RyevwVv2n1cSu4GewBn1WfKlVvYlNQ/85+ZdZO78x+KgsnMRaWZLfYnvT+YpzJjfDiorLrN1Hyr054sWNfQm7BfPqpi0dAhdOPgCJ4k5a8vySS2OcA6BJLiSR8qyeLQ7o2ndlV7DZGUxuV2ucRKVMGkswoJWougPhI6K/GWkEcLuiMp2OHLKdxHFlKw3VyIq0g4iNlodDediVn6V2N1b6U4h19gM+5b5+ma1p4iZLeaPryL26Ki0rWGvq+6jsQ0EuduFbTm5PqvP/N8k1ZI9D8PHxnaHkFxlDNJbjki3KJ7Lrhd1QGQJByhmYUJJUEKs0qOcULMUHJqBQs1cOqrhfLi3gc04O6fNTW25rPw1/iV7HVXtnkqZ29EUxOB5qLtNXeBsQO4z5BS07+JwYOaqO0ItO4cm2ATkZ6qrJXLJxXEcE04kF1IBLhnh5XQ9NXAlxr+zX+Wu08+AIlB6f7A9FM6RHGGr7SpKHvP/AG6SfxT2PGQUZRnKCai6Ldddc0GTInT3YchplNpx3CrH2nX0I70Y+CKiI5IRzc2tuiom2C1n2i/Q2AlC9oNWMbO7Y4gu3PQdFyvquBgIxxED3LO9o5bvPTFvgje+HnLU/soeTLPIfytA+uVvXrF/s1g4Y3HmbXW1evM8t7XqeL1lEmkpxTCsWvUUouFW1EKtChqhqqFWcq3AKmnmOyu9Ti6Ksho8rVlpFRQOcRmy00DQ0eaEp4w1TAm6Olzi50rLwVUdpf8AmHkbEqypZ2xtMjjYNaSslSaiJWlxOTM+1+h2V4lZeTSdJdsmhPiPR1kiuLpS5B8rHLpDcLi6zcKblpnyRqqH2AuuNylRsPAPRERU7+iMo8mkNikjfs7uiSfaz+UeGNKLpnZCDCKg3+C6qiLCUqXSj4ioXR39VJA9sXic65/KEs/Y1OrFpubAZUzpY2+07I3a3l6qim1c5sOG/IKu705JJzv5rT5JmR+qVxkdj2QcIXVsm/8ASFCHIiuOR6AKL7XG2/Z3L+7I81tV5J2Y1QwyjPhJsV6rTzh4BGxF1x+Se3f49dhzkxSKJ5WLQx5VfVS2RsjsKuqG3VSEqKyS6hgR01OFGyFUmntT2gJoFlW6rqQY02ObJ5nanXqBu1us2Z3DDk7kdFTUuKd1t+NtvIquleXOJO5vlW9Mz9yPOQFdmM8jj3rtWlRqsYDQR4rNDzfNzzRsADxxNPEP0WL1Gf8Aen3BG6fVyRtc9ruYFvJLWepmmoLEwhRUmrMePELO/VE8QtcbeSzuK1mpUVk6MG49QkSnRbj1Cj/R8bShNmj0CI71DUg8I9ApuFKfbKw/7Qkmd2ElfCeDxAuwNzyGVaRUwYAZTb+ke0nfao4xwxMzzkOSgJ3uebk3Pqt6UF1eoE4YLN6Dc+qDL1HslxIDsjce9cUvFhRgIDjURVG9vRBhxvYomR2AgGA2t6re9jtbuO6c7I2usE42Te+ewh7XWLeijeOtfHv417f3l0x7lgtE7bYDZm2/qC1tLq0Mgux4PqbFcuvHXXncqSaVCSuXJ353Say6ni+onAlLhsEayPCDrX2GU+FeAamdZDVpLuVrqteGeZPJZ6SUuyea6PHly+XaMDCuKB14P9rlUW/+ovSa9ha6I4OSD1W7nqqrzxSOVhRSgxOZzuCq+VlnG+91KzBuEEPdM4cNskH6Igai+MgXx0v9EFDlwPI/qoKp5LrJG2cNXG9oJPC7mDsSi6aEkg2/wsjSzAssTlXekaq5jQTkDcH+yi5VNV6BSSeEeinB81XabWMkaC0+5EcN+az5wUX70kHwHqkj5RPHiryuMKkc1DXIK3MTgqFzeYTmHmnPCCJuyTTY5ULXdTn6KV84tlMGOYSei7JO0WF8oeSqJwFCYnICxccXSIGVBC7Fip22QELTYoiOU7gkehsoGHxLs0XCbg46KLOnLVnDq07dnn35RsPampbzB9yoGPunJXC5utDJ2tqT+Ue5Az6zPJu/4CyrOEqeJthf6omSu67UvO5PJDwSXCZPOM3KGNSeSvibUtXUfwhBtdY3GFwp7IiUyHQ1HEPEPentsTgoctthT0QygC6E54T529UFM4hxvyuFI4kOuDz+CHqXFxJ53QE9M4/VWMNTbHIqtjFmp7Hc0g0OkaoYjYG7b7dFtqHUGvaHXv8AqF5fA/KuNL1Atfa+ErCeh/ampLJ/eruqSn4w+sYo5WqQLisBWmxRDchRzw32TI38kGdJHdRiMHdErhZzQEbYwOSluOiakmROiCidGRspyU0oNwBPLxbK40LiRA5HcJxsp4n3xdMqYbAke9Mpo/FjbCYWMLcX5IKtqr+FpwOifWVP8LeaBay5slAaFPHHbKcxgH+VM1iYRCIE3sp2sAXWtATkBC8ZT4MZXHpzNkFEj91AG596nemgc0G5IbEDqF1MnOQU9ougJRgeadG4gXUUhzZJx5JBP9sd1SUPAVxHBxCuJJIgcK45JJM3Gpy4kkCXVxJMnUlxJAdSC4kkZs2xXKbY+n9l1JMgaMj29ySSA6kkkgEF0pJIBoTguJIBySSSAa5OSSQCKc1JJIJ0kkk1P//Z

#
# Flags below are optional
#

# Includes an icon in the footer for each username you enter
footer-links:
  dribbble:
  email:
  facebook:
  flickr:
  github: jgcarrasco
  instagram:
  linkedin: jgcarrasco
  pinterest:
  rss: # just type anything here for a working RSS icon
  twitter: jgcarrasco42
  stackoverflow: # your stackoverflow profile, e.g. "users/50476/bart-kiers"
  youtube: # channel/<your_long_string> or user/<user-name>
  googleplus: # anything in your profile username that comes after plus.google.com/


# Enter your Disqus shortname (not your username) to enable commenting on posts
# You can find your shortname on the Settings page of your Disqus account
disqus:

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics:

# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
url: https://jgcarrasco.github.io

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: ""

#
# !! You don't need to change any of the configuration flags below !!
#

permalink: /:title/

# The release of Jekyll Now that you're using
version: v1.2.0

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

# Set the Sass partials directory, as we're using @imports
sass:
  style: :expanded # You might prefer to minify using :compressed

# Use the following plug-ins
gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
